apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: us-west-2

fargateProfiles:
  - name: fargate-productcatalog
    selectors:
      - namespace: workshop
        labels:
          app: prodcatalog

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: m5.large
    desiredCapacity: 2